highlighter: pygments
markdown: redcarpet
name: The OrgSync DevBlog
description: "OrgSync Developer Musings on: rails, ruby, testing, security, and development in general"
url: http://devblog.orgsync.com
permalink: pretty
timezone: America/Chicago

gems:
  - jekyll-redirect-from
  - jemoji
